site_name: P2 - Web Development
site_dir: public
repo_url: https://gitlab.inf.edt.cat/smx2/projectes/projectes-2425/g0/p2-web-development
repo_name: p2-web-development
docs_dir: ../docs
theme:
    language: ca
    name: material
    features:
        - navigation.instant
        - navigation.indexes
        - navigation.sections
        - navigation.path
        - header.autohide
        - search.highlight
        - search.suggest
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - content.code.copy
        - content.action.edit
    icon:
        repo: fontawesome/brands/git-alt
        edit: material/pencil
    palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:                 
      permalink: true
plugins:
    - mkdocs-video
    - search:
        lang:
            - es
            - en
            - ca
    - git-authors
    - git-revision-date-localized:
        enable_creation_date: true
nav:
    - Home: index.md
    - Documentació: demo/index.md
    - Codi:
        - Codi web: Codi/code.md
    - Problemes: Problemes/problems.md
    - Planificació: Planificació/schedule.md
    - Webgrafia: Webgrafia/webgrafia.md 